# Generated by Django 5.1 on 2025-07-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gallery_names',
            new_name='gallery_name',
        ),
        migrations.RenameModel(
            old_name='team_members',
            new_name='team_member',
        ),
    ]
